### ISSUE TITLE
to do note with reminder

### ISSUE THREAD

**Issue by swarnapriyakailasam** [firefox-addons/ideas#10]
here we can mention our daily activities or any important note to be reminded.alarms can be set as notifications.

**Comment by tsl143** [comment]
https://addons.mozilla.org/en-US/firefox/addon/todo/
Still just todo, I will try to add reminder functionality in next Iteration.

**Comment by tsl143** [comment]
https://addons.mozilla.org/en-US/firefox/addon/reminders/
