### ISSUE TITLE
Instant Dictionary

### ISSUE THREAD

**Issue by ram-sankar** [firefox-addons/ideas#13]
desc : my extension is about getting the meaning of a word without opening a new tab.
i.e if u select a word and hover over it then my extension will show the meaning of it.

https://chrome.google.com/webstore/detail/urban-dictionary-instant/iphhinkkgcndibcnabdcfcianhebblmb

**Comment by Mte90** [comment]
where is that extension on github? probably can be uploaded very easily on amo

**Comment by tsl143** [comment]
We have something similar that too with translation 
https://addons.mozilla.org/en-US/firefox/addon/dictionary-anywhere/
hence, closing this.
