### ISSUE TITLE
Identification and modification of Fonts

### ISSUE THREAD

**Issue by ParkaviRajanbabu** [firefox-addons/ideas#15]
A very simple method to identify and modify in any web pages

**Comment by iamVP7** [comment]
Can u ping in telegram

**Comment by Mte90** [comment]
uhm developers tool show what is the webfont and is very easy to change using the inspector so I think that can be closed.

**Comment by tsl143** [comment]
> uhm developers tool show what is the webfont and is very easy to change using the inspector so I think that can be closed.

closing on this context
