### ISSUE TITLE
Text Only Add on 

### ISSUE THREAD

**Issue by RudrThakur** [firefox-addons/ideas#16]
/* For slow data connections
Enabling this add on restricts the running of img tags irrespective of their role in the web page
so that the webpage can be loaded faster

/* Alternate Data Saver
Bandwidth used will also be less because of no images on the webpage

/*ACTUALLY ALREADY ITS AVAILABLE ON UC BROWSER */ as "text-only"
LINK - Can't find link ( If anyone gets post it as a comment )

/*ALSO AVAILABLE ON MOZILLA FIREFOX */ as "textize"
LINK -https://addons.mozilla.org/en-Us/firefox/addon/textise/

/*AND ALSO ON GOOGLE CHROME */ as "text mode"
LINK - https://chrome.google.com/webstore/detail/text-mode/adelhekhakakocomdfejiipdnaadiiib

**Comment by RudrThakur** [comment]
/* THE PROPOSED ADD ON FOR MOZILLA FIREFOX WAS SUCCESSFULLY DESIGNED */

/*Tested by me */

contains the following two files 

1. manifest.json
2.content_script.js

THE DESIGNED ADD ON does what ?

- open the website : "www.photobucket.com" in nightly mozilla 
- again open the same website in another web browser 
- Notice that all the pictures are shown in other web browser but nothing is shown in mozilla nightly 
because the add- on removed all the images 

/* ALL THE PROPOSED AIMS WERE ACHIEVED */

- Webpage loads faster 
- Consumed Bandwidth is less 

/*STILL IN DEVELOPMENT .... WILL BE BACK TO YOU AFTER SOME TWEAKS IN THE ADDON */

The ADDON is named after its role i.e "TEXTIFIER"
-------HOPE YOU LIKE IT ------------

**Comment by tsl143** [comment]
So its already built, so closing this
