### ISSUE TITLE
automatic wishes

### ISSUE THREAD

**Issue by rittikakamaraj** [firefox-addons/ideas#19]
type a message and set a timer
it will automatically send the message according to the timer

**Comment by iamVP7** [comment]
Just would like to know in which platform we will send the messages.. for timer checking alarm API https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/alarms

**Comment by rittikakamaraj** [comment]
we will use this in gmail...we can send wishes through gmail by setting the timer

**Comment by tsl143** [comment]
@rittikakamaraj , gmail already has this feature
https://www.labnol.org/internet/schedule-gmail-send-later/24867/

In case if there is something different, please feel free to reopen this.
