### ISSUE TITLE
YouTube to MP3 Converter

### ISSUE THREAD

**Issue by akshaykumar96** [firefox-addons/ideas#2]
Convert Youtube videos in Mp3 Format without leaving the Youtube page.

https://chrome.google.com/webstore/detail/youtube-to-mp3-converter/abhdmghdmjjbkahpebhjdofmcljkljbk

**Comment by iamVP7** [comment]
@akshaykumar96  this is nice idea. I think it will take more than a day to try. Can we run something easily ?

**Comment by devcer** [comment]
Is there any similar addon on chrome webstore? Cz this would be a direct violation against youtube for modifying the content.

**Comment by tsl143** [comment]
We have something like
website - http://keepvid.com/
third party extension - http://addoncrop.com/youtube-to-mp3-converter-direct/

**Comment by tsl143** [comment]
In addition we have youtube downloader addons already which downloads complete video in all formats.

**Comment by tsl143** [comment]
In addition we have youtube downloader addons already which downloads complete video in all formats.

**Comment by tsl143** [comment]
Guys I stumbled upon https://addons.mozilla.org/en-US/firefox/addon/easy-youtube-video-download

This downloads youtube videos in almost all necessary formats including mp3.

Hence closing this.
