### ISSUE TITLE
Addon which reminds me to drink water

### ISSUE THREAD

**Issue by devcer** [firefox-addons/ideas#24]
Takes the input of number of hours i would be awake and amount of water i should take. Constantly reminds me to drink water.

**Comment by Mte90** [comment]
it is not better a desktop applications for this?

**Comment by iamVP7** [comment]
When i work only in browser a notification + logging of time i drank will be great if it is in browser itself

**Comment by devcer** [comment]
I'm working on this idea. Might have a stable extension by this sunday.

**Comment by devcer** [comment]
I have a first version of this add-on.

https://github.com/viswanathamsantosh/hydrator

**Comment by caitmuenster** [comment]
Arg -- this might be me having technical difficulties but I wasn't able to install the add-on in Nightly because the "file was corrupt." Has anyone else been able to install this successfully?

**Comment by devcer** [comment]
Just now tested on 55.0b6 ! Which version were you testing on caitlin?

PS: updated some code for testing(15mins will be 30 seconds)

**Comment by iamVP7** [comment]
I checked and used the source code shared by Santhosh. Worked for me. I use nightly

**Comment by caitmuenster** [comment]
So sorry! This was definitely user error. I have it installed now and it's reminding me to drink water!

**Comment by devcer** [comment]
The add-on is being built and published to AMO< https://addons.mozilla.org/en-US/firefox/addon/hydrator >
