### ISSUE TITLE
Sticky notes

### ISSUE THREAD

**Issue by Balaji2198** [firefox-addons/ideas#4]
Easiest way for taking notes

https://chrome.google.com/webstore/detail/sticky-notes-just-popped/plpdjbappofmfbgdmhoaabefbobddchk

**Comment by tsl143** [comment]
We have already something for this
- https://addons.mozilla.org/en-US/firefox/addon/sticky_notes/
- https://addons.mozilla.org/en-US/firefox/addon/floating-sticky/
