### ISSUE TITLE
blind director

### ISSUE THREAD

**Issue by reminaagnes** [firefox-addons/ideas#6]
this addon is useful for the blind people to guide them in reaching their home safely.

**Comment by iamVP7** [comment]
@reminaagnes  we are targeting only the desktop browser. I hope there is dependency of mobile here. Can you rethink.

**Comment by tsl143** [comment]
Not in scope.

**Comment by devcer** [comment]
All the computers are already integrated with accessibility tools(eg: voiceover for ios)  which will work with all applications so add-on is not required.
