### ISSUE TITLE
propose to github monetizing its content and paying people

### ISSUE THREAD

**Issue by ghost** [firefox-addons/ideas#70]
#### propose to github monetizing its content and paying people

**the idea would be monetizing content in github, and paying people in function of:**
- *the games would be monetized with ads, all the content would be free, and people would be paid in function of their amount and quality of contributions, instead of visualizations and usage of their content*
- *this would be automatically evaluated throughout AI*

**Comment by tsl143** [comment]
@tmm2018, This repository is for collecting ideas on which addons can be built, I am not sure if this qualifies for any addon.
Please feel free to reopen , if otherwise
