### ISSUE TITLE
Translator

### ISSUE THREAD

**Issue by Swathidivya** [firefox-addons/ideas#8]
Translates each and every hindi words into English or Tamil..
With a common man understable....

**Comment by reminaagnes** [comment]
its just kind of a dictionary

**Comment by iamVP7** [comment]
@Swathidivya  will you be using any transaltor or words will be predefined.

**Comment by Swathidivya** [comment]
words will be predefined at first itself...

**Comment by tsl143** [comment]
https://addons.mozilla.org/en-US/firefox/addon/google-translator-lite/, solves same purpose.
