### ISSUE TITLE
colorPicker

### ISSUE THREAD

**Issue by iamVP7** [firefox-addons/ideas#80]
https://addons.mozilla.org/en-US/firefox/addon/colorpicker/

**Comment by tsl143** [comment]
@iamVP7 , I am shocked, previously there was an eyedropper tool in Firefox, that does same thing as this, I think it has been removed already, but no where mentioned - https://developer.mozilla.org/en-US/docs/Tools/Eyedropper

**Comment by tsl143** [comment]
I found that :)
So this is default Firefox tool now. Please find it in attached screenshot. Use it to get colors from any page.

![screen shot 2018-01-09 at 4](https://user-images.githubusercontent.com/5318732/34717541-738924a6-f559-11e7-8987-5d6d2d20500e.png)

**Comment by iamVP7** [comment]
I thought this add-on should be ported. Think of the first time Front end developer (who has not touched dev tools), for him / her if this add-on is there then he can clock on browserAction icon, and click on page so he gets the hex code.
