### ISSUE TITLE
Dynamic Theme Based on Weather

### ISSUE THREAD

**Issue by caitmuenster** [firefox-addons/ideas#85]
It would be really cool to have a dynamic theme that changes based on the weather.

**Comment by nt1m** [comment]
Wish granted: https://addons.mozilla.org/en-US/firefox/addon/weatherlicious/

**Comment by caitmuenster** [comment]
![yes-pumpedup](https://user-images.githubusercontent.com/23342476/37837595-d94c1850-2e72-11e8-8298-6bc2a548e4a7.gif)

Would you be interested in entering this or another extension in the Firefox Quantum Extensions Challenge? https://extensionschallenge.com/

**Comment by nt1m** [comment]
@caitmuenster Done :)
